---
title: "PICO 2: Main Forest Plots"
author: "Rune Haubo B Christensen & Sabine Færge"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

## Setup

```{r setup0, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

Load packages:
```{r, warning=FALSE, message=FALSE}
library(meta)
library(grid)
library(ggplot2)
library(data.table)
```

Read functions: 
```{r, include_functions}
source("functions/meta_analysis_functions.R")
source("functions/misc_functions.R")
source("functions/format_functions.R")
```


## Read data

```{r}
d3 <- readRDS("data_derived/pico2_3.rds")
```

```{r functions}
rescale_means <- function(object) {
  object$mean.e <- abs(object$mean.e)
  object$mean.c <- abs(object$mean.c)
  object
}
mk_plot <- function(meta_obj, width=12, height=10, 
                    save_fig = interactive(), fig_path="figures/test01.pdf", ...) {
  if(save_fig) pdf(fig_path, width=width, height=height)
  
  forest(rescale_means(meta_obj), 
         digits.sd = 1, 
         digits.mean = 2, 
         xlim=c(-2, 2), 
         
         # Column labels: 
         leftcols = c("studlab", "outcome", "disease", "n.e", "mean.e", "sd.e", 
                      "n.c", "mean.c", "sd.c"),
         leftlabs = c("Study", "Outcome", "Population", "Total", "Mean", "SD", 
                      "Total", "Mean", "SD"),
         just.addcols.left = "right",
         rightcols = c("effect", "ci", "w.random"),
         
         # Overall/Random/Common effect settings:
         overall = FALSE,
         common = FALSE,
         random = TRUE,
         overall.hetstat = FALSE,
         hetstat = TRUE,
         test.overall.random = FALSE,
         
         # Subgroup settings:
         subgroup = TRUE,
         print.subgroup.name = FALSE,
         random.subgroup = TRUE,
         test.subgroup = FALSE,
         test.effect.subgroup = TRUE,
         label.test.effect.subgroup.random = "Test of random effect: ",
         
         # Prediction interval settings:
         prediction = FALSE,
         prediction.subgroup = TRUE
)
  
  if(save_fig) dev.off()
  invisible(NULL)
}
```


## Psychometrics

Extract data for the psychometrics outcome category. For each combination of study, outcome and disease, select the data row where follow-up is closest to duration of the trial:
```{r}
d4 <- d3[outcome.cat == "psychometrics" & include == 1]
d4[, grp := .GRP, by=.(author, year, outcome, disease)]
d4[, n.outcome.subcat := .N, outcome.subcat]
d4 <- d4[n.outcome.subcat > 1, .SD[which.min(abs(duration - followup))], by=grp]

setorder(d4, -year)
```

```{r fig.width=13, fig.height=10}
meta_obj <- metacont(n.e    = n.e, 
                     mean.e = eot.m.e * direction, 
                     sd.e   = eot.sd.e, 
                     n.c    = n.c, 
                     mean.c = eot.m.c * direction, 
                     sd.c   = eot.sd.c, 
                     studlab=paste0(author, " ", year),
                     subgroup = outcome.subcat,
                     data=d4,
                     sm="SMD") 
mk_plot(meta_obj, width = 13, height=10)
```


## Biomarkers

Extract data for biomarkers:
```{r, results='hide'}
d4 <- d3[
  outcome.cat != "psychometrics" &
  include == 1 &
  !is.na(eot.m.e) &
  !is.na(eot.sd.c) &
  eot.sd.c > 0
]

d4[, grp := .GRP, by = .(author, year, outcome, disease)]
d4 <- d4[, .SD[which.min(abs(duration - followup))], by = grp]
setorder(d4, -year)

d4[, n_studies := .N, keyby=outcome]
d5 <- d4[n_studies > 1] |> droplevels()
outcome_levels <- d5[, .N, outcome][order(-N)][, outcome]
d5[, f_outcome := factor(outcome, levels = outcome_levels)]
d5[, .N, keyby = f_outcome]
```

```{r fig.width=13.5, fig.height=31}
meta_obj <- metacont(n.e    = n.e, 
                     mean.e = eot.m.e * direction, 
                     sd.e   = eot.sd.e, 
                     n.c    = n.c, 
                     mean.c = eot.m.c * direction, 
                     sd.c   = eot.sd.c, 
                     studlab=paste0(author, " ", year),
                     subgroup = f_outcome,
                     data=d5,
                     sm="SMD") 
mk_plot(meta_obj, width = 13.5, height=31)
```


## Appendix

**R** session info:
```{r}
sessionInfo()
```












